In [23]:
import numpy as np
from scipy.special import binom
print('imports done.')

imports done.


In [127]:
def payoff_EC(K,ST):
    if type(ST) == float or type(ST)==np.float64:
        return max(ST-K,0)
    else:

        return np.maximum(ST-K*np.ones(len(ST)),np.zeros(len(ST)))
    
def payoff_ECPower(K,ST,p):
    if type(ST) == float or type(ST)==np.float64:
        return max(ST-K,0)**p
    else:
        return np.maximum(ST-K*np.ones(len(ST)),np.zeros(len(ST))**p)

def payoff_AP(K,ST):
    return max(K-ST,0)

In [123]:
T = 1
n = 2
delta = T/n
K = 100
r = 0.05
S0 = 90 
sigma = 0.3

u = np.exp(sigma*np.sqrt(delta))
d = 1/u

qu = (np.exp(r*delta)-d)/(u-d)
qd = 1-qu

binmat = np.zeros((n+1,n+1))

for j in range(n+1):
    for i in range(n+1):
        if i <= j:
            binmat[i,j] = S0*u**(j-i)*d**(i)
print(binmat)

[[ 90.         111.26799989 137.56186443]
 [  0.          72.79721041  90.        ]
 [  0.           0.          58.88259827]]


In [136]:
u

1.2363111098437878

In [131]:
# Å 3.3
price = 0.0
for k in range(n+1):
    price += binom(n,k)*qu**(n-k)*qd**k*payoff_ECPower(K,binmat[k,-1],1)
price = price*np.exp(-r*T)
print(price)


9.162192651066093


In [132]:
# RNVF
price = 0.0
for k in range(n+1):
    price += binom(n,k)*qu**(n-k)*qd**k*payoff_EC(K,binmat[k,-1])
price = price*np.exp(-r*T)
print(price)

9.162192651066093


In [119]:
# EC using nodes
pricemat = np.zeros((n+1,n+1))
pricemat[:,-1] = payoff_EC(K,binmat[:,-1])
for k in range(n-1,-1,-1):
    for j in range(k+1):
        pricemat[j,k] = np.exp(-r*delta)*(qu*pricemat[j,k+1]+qd*pricemat[j+1,k+1])
        
pricemat

array([[ 4.56030909,  8.28350001, 15.03339534, 27.25842123],
       [ 0.        ,  0.29059823,  0.54338882,  1.01608122],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])